### PR TITLE
fix broken vpc diagram 

### PR DESCRIPTION
**Pull request by emalloy**
fix broken vpc diagram - closes issue #28

### CODE REVIEW

**Comment by philipcristiano** [comment]
Thanks! Is there a smaller resolution/larger text version we can use that might be more legible on the page? I have to zoom about 250% to read the image

**Comment by emalloy** [comment]
I do not .. not without creating a new from scratch or trying to manipulate this png. @sairez Do you have the original in your cloudcraft account? I guess this image kept getting removed wherever we stored it remotely. I guess we should just commit it to git. No rush -

**Comment by sairez** [comment]
I do not. This was created by a former employee. I do, however have a lucidchart version

**Comment by emalloy** [comment]
@sairez Even better! Can you drop it in the 'Reactiveops' Lucidchart folder when you get a chance?

**Pull request merged**
